# Activaty-1
# class Emplopee:
#     def __init__(self):
#         print("emplopee created")
#     def __del__(self):
#         print("emplopee fired and destored")
# obs = Emplopee()
# del obs

# Activaty-2

class Libary:
    def __init__(self, name):
        self.name = name
        self.lended_books = 0
        self.books = [
    "Pride and Prejudice",
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Moby Dick",
    "War and Peace",
    "Anna Karenina",
    "Crime and Punishment",
    "The Brothers Karamazov",
    "Ulysses",
    "Don Quixote",
    "One Hundred Years of Solitude",
    "The Catcher in the Rye",
    "Brave New World",
    "The Hobbit",
    "The Lord of the Rings",
    "Jane Eyre",
    "Wuthering Heights",
    "Great Expectations",
    "Alice's Adventures in Wonderland",
    "Frankenstein",
    "Dracula",
    "The Picture of Dorian Gray",
    "Les Misérables",
    "The Count of Monte Cristo",
    "The Adventures of Huckleberry Finn",
    "A Tale of Two Cities",
    "Heart of Darkness",
    "The Odyssey",
    "The Iliad",
    "Invisible Man",
    "Beloved",
    "Slaughterhouse‑Five",
    "Catch‑22",
    "Lolita",
    "The Sound and the Fury",
    "The Grapes of Wrath",
    "East of Eden",
    "The Sun Also Rises",
    "On the Road",
    "The Old Man and the Sea",
    "For Whom the Bell Tolls",
    "The Scarlet Letter",
    "Little Women",
    "Sense and Sensibility",
    "Emma",
    "Persuasion",
    "Northanger Abbey",
    "Middlemarch",
    "Tess of the d'Urbervilles",
    "Fahrenheit 451",
    "Brideshead Revisited",
    "A Farewell to Arms",
    "Gone with the Wind",
    "Rebecca",
    "The Kite Runner",
    "Life of Pi",
    "The Alchemist",
    "The Road",
    "Bel Canto",
    "The Handmaid's Tale",
    "The Hunger Games",
    "Harry Potter and the Sorcerer’s Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half‑Blood Prince",
    "Harry Potter and the Deathly Hallows",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "The Chronicles of Narnia: Prince Caspian",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "The Chronicles of Narnia: The Silver Chair",
    "The Chronicles of Narnia: The Horse and His Boy",
    "The Chronicles of Narnia: The Magician’s Nephew",
    "The Chronicles of Narnia: The Last Battle",
    "A Game of Thrones",
    "A Clash of Kings",
    "A Storm of Swords",
    "A Feast for Crows",
    "A Dance with Dragons",
    "The Girl with the Dragon Tattoo",
    "The Da Vinci Code",
    "Angels & Demons",
    "The Fault in Our Stars",
    "The Book Thief",
    "The Help",
    "Gone Girl",
    "The Shining",
    "It",
    "The Stand",
    "The Road to Kindness",
    "Memoirs of a Geisha",
    "The Color Purple",
    "The Bell Jar",
    "Atonement",
    "The Goldfinch",
    "All the Light We Cannot See",
    "The Shadow of the Wind",
    "The Night Circus",
    "The Nightingale",
    "Water for Elephants",
    "The Time Traveler’s Wife",
    "The Pillars of the Earth",
    "World Without End",
    "Sapiens: A Brief History of Humankind",
    "Homo Deus",
    "The Catcher Was a Spy",
    "The Immortal Life of Henrietta Lacks",
    "A Little Life",
    "Normal People",
    "Circe",
    "The Song of Achilles",
    "Where the Crawdads Sing",
    "The Underground Railroad",
    "Station Eleven",
    "The Goldfinch",
    "The Girl on the Train",
    "Big Little Lies",
    "The Secret History",
    "The Shadow Rising",
    "The Wise Man’s Fear",
    "The Name of the Wind",
    "The Priory of the Orange Tree",
    "The Fifth Season",
    "The Broken Earth Trilogy: The Obelisk Gate",
    "The Broken Earth Trilogy: The Stone Sky",
    "The Way of Kings",
    "Words of Radiance",
    "Oathbringer",
    "Rhythm of War",
    "Mistborn: The Final Empire",
    "Mistborn: The Well of Ascension",
    "Mistborn: The Hero of Ages",
    "Elantris",
    "Warbreaker",
    "The Lies of Locke Lamora",
    "Red Seas Under Red Skies",
    "The Republic of Thieves",
    "The Wise Man’s Fear",
    "The Name of the Wind",
    "The Slow Regard of Silent Things",
    "Hyperion",
    "The Fall of Hyperion",
    "Ender's Game",
    "Speaker for the Dead",
    "Xenocide",
    "Children of the Mind",
    "Dune",
    "Dune Messiah",
    "Children of Dune",
    "God Emperor of Dune",
    "Heretics of Dune",
    "Chapterhouse: Dune",
    "Foundation",
    "Foundation and Empire",
    "Second Foundation",
    "Prelude to Foundation",
    "Forward the Foundation",
    "The Left Hand of Darkness",
    "The Dispossessed",
    "The Moon is a Harsh Mistress",
    "The Forever War",
    "Snow Crash",
    "Neuromancer",
    "Do Androids Dream of Electric Sheep?",
    "Ubik",
    "The Road",
    "Blindness",
    "The Wind‑Up Bird Chronicle",
    "Kafka on the Shore",
    "Norwegian Wood",
    "1Q84",
    "The Brothers Grimm Fairy Tales",
    "Grimm’s Complete Fairy Tales",
    "The Very Hungry Caterpillar",
    "Charlotte’s Web",
    "Where the Wild Things Are",
    "Goodnight Moon",
    "Green Eggs and Ham",
    "The Cat in the Hat",
    "Oh, the Places You’ll Go!",
    "Matilda",
    "The Chronicles of Prydain: The Book of Three",
    "The Chronicles of Prydain: The Black Cauldron",
    "The Chronicles of Prydain: The Castle of Llyr",
    "The Chronicles of Prydain: Taran Wanderer",
    "The Chronicles of Prydain: The High King"  
    ]
        self.lend_data = {}
    
    def desplay_books(self):
        print("\n📖 Available Books:")
        for book in self.books:
            print(f" -{book}")
    def lend_book(self, user, book):
        if book not in self.books:
            print(f"❌ The book {book} is not available in this libary.")
        elif book in self.lend_data:
            print(f"⚠️ Sorry '{book}' is currently lend out to {self.lend_data[book]}.")
        else:
            if self.lended_books >= 10:
########################################################################################################################
                print("Sorry you can not lend any more books until you return on of the following:")
###################################################################################################################
            self.lend_data[book] = user
            self.lended_books += 1
            print(f"✅ Book successfully lend to {self.lend_data[book]}.")
            print(f"You currently have {self.lended_books} lended books")
    

